@Create the pom and the helloWorld.kt
0riginz/C0ffe1sWh8tWeNeed pull request #6
Opened 2017-08-07 10:34 UTC by chris0197

@nicolaiparlog

2017-08-07 11:31 UTC, nicolaiparlog commented
Create and link to an issue as described [here](https://github.com/0riginz/C0ffe1sWh8tWeNeed/pull/5#issuecomment-320639589).

2017-08-07 11:32 UTC, nicolaiparlog commented on Main.kt
> +package FinalProject
Package names are by convention entirely lower cased (e.g. `finalproject` or maybe `final_project`). Generally speaking, something like `traffic` might make more sense.

2017-08-07 11:39 UTC, nipafx requested changes

2017-08-07 11:39 UTC, nicolaiparlog commented on pom.xml
> +        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
Here you define (correctly) where to find source files but `Main.kt` is not in there. Once you fix that, the build works.

2017-08-08 09:23 UTC, nicolaiparlog commented
The README changes you added in 1280ffd do not belong into this pull request.

2017-08-09 10:01 UTC, chris0197 commented
@nicolaiparlog added some changes to the pom.xml

2017-08-09 10:13 UTC, nicolaiparlog commented
I don't see it in this pull request.

2017-08-09 10:14 UTC, nicolaiparlog commented
Also, you still need to link to the issue...

2017-08-09 10:30 UTC, chris0197 commented
@nicolaiparlog
 i changed the file over git and use mvn clean install (showed Hello World) after that i pushed the pom and src folder

2017-08-09 10:38 UTC, nicolaiparlog commented
> after that i pushed the pom and src folder

But apparently not to this branch or you got an error message that you ignored, or... many things can go wrong but the fact is, the commit is not in this pull request.

Have a look at what's above [this comment](https://github.com/0riginz/C0ffe1sWh8tWeNeed/pull/6#issuecomment-320901422) (scroll up a little). What you see there is a commit that was added to this PR by pushing the `chris0197-patch-3` branch. Since then no new commits were added, so there are no changes for me to review.

2017-08-09 10:40 UTC, chris0197 commented
@nicolaiparlog forgot to commit...

2017-08-09 10:48 UTC, chris0197 commented
commit and push were successfully merged by accident but should be right....
sorry

2017-08-09 10:53 UTC, nicolaiparlog commented
You need to improve your Git/GitHub abilities. One rule of thumb: When you're trying to merge anything on the command line, chances are high, you're doing something wrong.

2017-08-09 10:53 UTC, closed without merging